package takap.mods.nnnpc.extension.majokko;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMajokko extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer neck;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer fronthair1;
    ModelRenderer fronthair2;
    ModelRenderer fronthair3;
    ModelRenderer fronthair4;
    ModelRenderer rearhair1;
    ModelRenderer rearhair2;
    ModelRenderer righthair1;
    ModelRenderer righthair2;
    ModelRenderer lefthair1;
    ModelRenderer lefthair2;
    ModelRenderer blouse;
    ModelRenderer rightblouse;
    ModelRenderer leftblouse;
    ModelRenderer pants;
    ModelRenderer rightpants;
    ModelRenderer leftpants;
    ModelRenderer rightshoe;
    ModelRenderer leftshoe;
    ModelRenderer frontskirt;
    ModelRenderer rearskirt;
    ModelRenderer rightskirt;
    ModelRenderer leftskirt;
    ModelRenderer frontvest1;
    ModelRenderer rearvest;
    ModelRenderer rightvest;
    ModelRenderer leftvest;
    ModelRenderer rightshouldervest;
    ModelRenderer leftshouldervest;
    ModelRenderer apronribon1;
    ModelRenderer apronribon2;
    ModelRenderer apronribon3;
    ModelRenderer apronribon4;
    ModelRenderer apronribon5;
    ModelRenderer apronribon6;
    ModelRenderer apronribon7;
    ModelRenderer brim;
    ModelRenderer crown1;
    ModelRenderer crown2;
    ModelRenderer crown3;
    ModelRenderer crown4;
    ModelRenderer crown5;
  
    public ModelMajokko()
    {
        textureWidth = 256;
        textureHeight = 128;
    
        head = new ModelRenderer(this, 0, 0);
        head.addBox(-4F, -8.5F, -4F, 8, 8, 8);
        head.setRotationPoint(0F, 8F, 0F);
        head.setTextureSize(256, 128);
        setRotation(head, 0F, 0F, 0F);
        neck = new ModelRenderer(this, 32, 0);
        neck.addBox(-1F, -1.5F, -1F, 2, 2, 2);
        neck.setRotationPoint(0F, 8F, 0F);
        neck.setTextureSize(256, 128);
        setRotation(neck, 0F, 0F, 0F);
        body = new ModelRenderer(this, 32, 4);
        body.addBox(-3F, 0F, -1.5F, 6, 8, 3);
        body.setRotationPoint(0F, 8F, 0F);
        body.setTextureSize(256, 128);
        setRotation(body, 0F, 0F, 0F);
        rightarm = new ModelRenderer(this, 52, 0);
        rightarm.addBox(-3F, -1.5F, -1.5F, 3, 8, 3);
        rightarm.setRotationPoint(-3F, 9.5F, 0F);
        rightarm.setTextureSize(256, 128);
        setRotation(rightarm, 0F, 0F, 0.122173F);
        leftarm = new ModelRenderer(this, 52, 0);
        leftarm.addBox(0F, -1.5F, -1.5F, 3, 8, 3);
        leftarm.setRotationPoint(3F, 9.5F, 0F);
        leftarm.setTextureSize(256, 128);
        leftarm.mirror = true;
        setRotation(leftarm, 0F, 0F, -0.122173F);
        rightleg = new ModelRenderer(this, 64, 0);
        rightleg.addBox(-1.8F, 0F, -1.5F, 3, 8, 3);
        rightleg.setRotationPoint(-1.5F, 16F, 0F);
        rightleg.setTextureSize(256, 128);
        setRotation(rightleg, 0F, 0F, 0F);
        leftleg = new ModelRenderer(this, 64, 0);
        leftleg.addBox(-1.2F, 0F, -1.5F, 3, 8, 3);
        leftleg.setRotationPoint(1.5F, 16F, 0F);
        leftleg.setTextureSize(256, 128);
        leftleg.mirror = true;
        setRotation(leftleg, 0F, 0F, 0F);
        fronthair1 = new ModelRenderer(this, 44, 16);
        fronthair1.addBox(2.5F, -7.5F, -4.5F, 1, 6, 1);
        fronthair1.setRotationPoint(0F, 8F, 0F);
        fronthair1.setTextureSize(256, 128);
        setRotation(fronthair1, 0F, 0F, 0F);
        fronthair2 = new ModelRenderer(this, 44, 16);
        fronthair2.addBox(0.5F, -7.5F, -4.5F, 1, 3, 1);
        fronthair2.setRotationPoint(0F, 8F, 0F);
        fronthair2.setTextureSize(256, 128);
        setRotation(fronthair2, 0F, 0F, 0F);
        fronthair3 = new ModelRenderer(this, 44, 16);
        fronthair3.addBox(-1.5F, -7.5F, -4.5F, 1, 2, 1);
        fronthair3.setRotationPoint(0F, 8F, 0F);
        fronthair3.setTextureSize(256, 128);
        setRotation(fronthair3, 0F, 0F, 0F);
        fronthair4 = new ModelRenderer(this, 44, 16);
        fronthair4.addBox(-3.5F, -7.5F, -4.5F, 1, 6, 1);
        fronthair4.setRotationPoint(0F, 8F, 0F);
        fronthair4.setTextureSize(256, 128);
        setRotation(fronthair4, 0F, 0F, 0F);
        rearhair1 = new ModelRenderer(this, 14, 16);
        rearhair1.addBox(-3F, -7.5F, 3.5F, 6, 8, 1);
        rearhair1.setRotationPoint(0F, 8F, 0F);
        rearhair1.setTextureSize(256, 128);
        setRotation(rearhair1, 0F, 0F, 0F);
        rearhair2 = new ModelRenderer(this, 28, 16);
        rearhair2.addBox(-3.5F, -8F, 2.7F, 7, 9, 1);
        rearhair2.setRotationPoint(0F, 8F, 0F);
        rearhair2.setTextureSize(256, 128);
        setRotation(rearhair2, 0F, 0F, 0F);
        righthair1 = new ModelRenderer(this, 16, 0);
        righthair1.addBox(-4.5F, -7.5F, -3F, 1, 6, 6);
        righthair1.setRotationPoint(0F, 8F, 0F);
        righthair1.setTextureSize(256, 128);
        setRotation(righthair1, 0F, 0F, 0F);
        righthair2 = new ModelRenderer(this, 44, 16);
        righthair2.addBox(-3.5F, -2F, -3F, 1, 4, 1);
        righthair2.setRotationPoint(0F, 8F, 0F);
        righthair2.setTextureSize(256, 128);
        setRotation(righthair2, 0F, 0F, 0F);
        lefthair1 = new ModelRenderer(this, 16, 0);
        lefthair1.addBox(3.5F, -7.5F, -3F, 1, 6, 6);
        lefthair1.setRotationPoint(0F, 8F, 0F);
        lefthair1.setTextureSize(256, 128);
        lefthair1.mirror = true;
        setRotation(lefthair1, 0F, 0F, 0F);
        lefthair2 = new ModelRenderer(this, 48, 16);
        lefthair2.addBox(2.5F, -2F, -3F, 1, 4, 1);
        lefthair2.setRotationPoint(0F, 8F, 0F);
        lefthair2.setTextureSize(256, 128);
        lefthair2.mirror = true;
        setRotation(lefthair2, 0F, 0F, 0F);
        blouse = new ModelRenderer(this, 0, 32);
        blouse.addBox(-3.5F, -0.1F, -2F, 7, 8, 4);
        blouse.setRotationPoint(0F, 8F, 0F);
        blouse.setTextureSize(256, 128);
        setRotation(blouse, 0F, 0F, 0F);
        rightblouse = new ModelRenderer(this, 64, 32);
        rightblouse.addBox(-4F, -1.8F, -2F, 4, 3, 4);
        rightblouse.setRotationPoint(-3F, 9.5F, 0F);
        rightblouse.setTextureSize(256, 128);
        setRotation(rightblouse, 0F, 0F, 0.122173F);
        leftblouse = new ModelRenderer(this, 64, 32);
        leftblouse.addBox(0F, -1.8F, -2F, 4, 3, 4);
        leftblouse.setRotationPoint(3F, 9.5F, 0F);
        leftblouse.setTextureSize(256, 128);
        leftblouse.mirror = true;
        setRotation(leftblouse, 0F, 0F, -0.122173F);
        pants = new ModelRenderer(this, 24, 32);
        pants.addBox(-3.5F, -1F, -2F, 7, 2, 4);
        pants.setRotationPoint(0F, 16F, 0F);
        pants.setTextureSize(256, 128);
        setRotation(pants, 0F, 0F, 0F);
        rightpants = new ModelRenderer(this, 48, 32);
        rightpants.addBox(-2.5F, 0F, -2F, 4, 4, 4);
        rightpants.setRotationPoint(-1.5F, 16F, 0F);
        rightpants.setTextureSize(256, 128);
        setRotation(rightpants, 0F, 0F, 0F);
        leftpants = new ModelRenderer(this, 48, 32);
        leftpants.addBox(-1.5F, 0F, -2F, 4, 4, 4);
        leftpants.setRotationPoint(1.5F, 16F, 0F);
        leftpants.setTextureSize(256, 128);
        leftpants.mirror = true;
        setRotation(leftpants, 0F, 0F, 0F);
        rightshoe = new ModelRenderer(this, 24, 39);
        rightshoe.addBox(-2.5F, 6.1F, -2.2F, 4, 2, 4);
        rightshoe.setRotationPoint(-1.5F, 16F, 0F);
        rightshoe.setTextureSize(256, 128);
        setRotation(rightshoe, 0F, 0F, 0F);
        leftshoe = new ModelRenderer(this, 24, 39);
        leftshoe.addBox(1.5F, 6.1F, -2.2F, 4, 2, 4);
        leftshoe.setRotationPoint(-1.5F, 16F, 0F);
        leftshoe.setTextureSize(256, 128);
        leftshoe.mirror = true;
        setRotation(leftshoe, 0F, 0F, 0F);
        frontskirt = new ModelRenderer(this, 0, 72);
        frontskirt.addBox(-3.5F, -0.5F, -2.7F, 7, 6, 1);
        frontskirt.setRotationPoint(0F, 16F, 0F);
        frontskirt.setTextureSize(256, 128);
        setRotation(frontskirt, -0.2617994F, 0F, 0F);
        rearskirt = new ModelRenderer(this, 0, 79);
        rearskirt.addBox(-3.5F, -0.5F, 1.7F, 7, 6, 1);
        rearskirt.setRotationPoint(0F, 16F, 0F);
        rearskirt.setTextureSize(256, 128);
        setRotation(rearskirt, 0.2617994F, 0F, 0F);
        rightskirt = new ModelRenderer(this, 16, 72);
        rightskirt.addBox(-3.9F, 0F, -2.5F, 1, 6, 5);
        rightskirt.setRotationPoint(0F, 16F, 0F);
        rightskirt.setTextureSize(256, 128);
        setRotation(rightskirt, 0F, 0F, 0.296706F);
        leftskirt = new ModelRenderer(this, 16, 72);
        leftskirt.addBox(2.9F, 0F, -2.5F, 1, 6, 5);
        leftskirt.setRotationPoint(0F, 16F, 0F);
        leftskirt.setTextureSize(256, 128);
        leftskirt.mirror = true;
        setRotation(leftskirt, 0F, 0F, -0.296706F);
        frontvest1 = new ModelRenderer(this, 0, 64);
        frontvest1.addBox(-3F, 1.2F, -2.5F, 6, 6, 1);
        frontvest1.setRotationPoint(0F, 8F, 0F);
        frontvest1.setTextureSize(256, 128);
        setRotation(frontvest1, 0F, 0F, 0F);
        rearvest = new ModelRenderer(this, 16, 64);
        rearvest.addBox(-3F, 1.2F, 1.5F, 6, 6, 1);
        rearvest.setRotationPoint(0F, 8F, 0F);
        rearvest.setTextureSize(256, 128);
        setRotation(rearvest, 0F, 0F, 0F);
        rightvest = new ModelRenderer(this, 46, 64);
        rightvest.addBox(-3.6F, 4.2F, -2.5F, 1, 3, 5);
        rightvest.setRotationPoint(0F, 8F, 0F);
        rightvest.setTextureSize(256, 128);
        setRotation(rightvest, 0F, 0F, 0F);
        leftvest = new ModelRenderer(this, 46, 64);
        leftvest.addBox(2.6F, 4.2F, -2.5F, 1, 3, 5);
        leftvest.setRotationPoint(0F, 8F, 0F);
        leftvest.setTextureSize(256, 128);
        leftvest.mirror = true;
        setRotation(leftvest, 0F, 0F, 0F);
        rightshouldervest = new ModelRenderer(this, 46, 64);
        rightshouldervest.addBox(-3F, -0.2F, -2.5F, 1, 2, 5);
        rightshouldervest.setRotationPoint(0F, 8F, 0F);
        rightshouldervest.setTextureSize(256, 128);
        setRotation(rightshouldervest, 0F, 0F, 0F);
        leftshouldervest = new ModelRenderer(this, 46, 64);
        leftshouldervest.addBox(2F, -0.2F, -2.5F, 1, 2, 5);
        leftshouldervest.setRotationPoint(0F, 8F, 0F);
        leftshouldervest.setTextureSize(256, 128);
        setRotation(leftshouldervest, 0F, 0F, 0F);
        leftshouldervest.mirror = true;
        apronribon1 = new ModelRenderer(this, 28, 75);
        apronribon1.addBox(0.5F, -0.5F, 0F, 3, 1, 1);
        apronribon1.setRotationPoint(0F, 14.5F, 2.5F);
        apronribon1.setTextureSize(256, 128);
        setRotation(apronribon1, 0F, -0.3490659F, -0.2617994F);
        apronribon2 = new ModelRenderer(this, 28, 75);
        apronribon2.addBox(0.5F, -0.5F, 0F, 3, 1, 1);
        apronribon2.setRotationPoint(0F, 14.5F, 2.5F);
        apronribon2.setTextureSize(256, 128);
        setRotation(apronribon2, 0F, -0.3490659F, 0.6981317F);
        apronribon3 = new ModelRenderer(this, 28, 77);
        apronribon3.addBox(2.5F, -2.1F, 0F, 1, 4, 1);
        apronribon3.setRotationPoint(0F, 14.5F, 2.5F);
        apronribon3.setTextureSize(256, 128);
        setRotation(apronribon3, 0F, -0.3490659F, 0.2617994F);
        apronribon4 = new ModelRenderer(this, 28, 75);
        apronribon4.addBox(-3.5F, -0.5F, 0F, 3, 1, 1);
        apronribon4.setRotationPoint(0F, 14.5F, 2.5F);
        apronribon4.setTextureSize(256, 128);
        setRotation(apronribon4, 0F, 0.3490659F, 0.2617994F);
        apronribon5 = new ModelRenderer(this, 28, 75);
        apronribon5.addBox(-3.5F, -0.5F, 0F, 3, 1, 1);
        apronribon5.setRotationPoint(0F, 14.5F, 2.5F);
        apronribon5.setTextureSize(256, 128);
        setRotation(apronribon5, 0F, 0.3490659F, -0.6981317F);
        apronribon6 = new ModelRenderer(this, 28, 77);
        apronribon6.addBox(-3.5F, -2.1F, 0F, 1, 4, 1);
        apronribon6.setRotationPoint(0F, 14.5F, 2.5F);
        apronribon6.setTextureSize(256, 128);
        setRotation(apronribon6, 0F, 0.3490659F, -0.2617994F);
        apronribon7 = new ModelRenderer(this, 28, 72);
        apronribon7.addBox(-1F, -1F, 0F, 2, 2, 1);
        apronribon7.setRotationPoint(0F, 14.5F, 2.5F);
        apronribon7.setTextureSize(256, 128);
        setRotation(apronribon7, 0F, 0F, 0F);
        brim = new ModelRenderer(this, 0, 48);
        brim.addBox(-6F, -9F, -6F, 12, 1, 12);
        brim.setRotationPoint(0F, 8F, 0F);
        brim.setTextureSize(256, 128);
        setRotation(brim, 0F, 0F, 0F);
        crown1 = new ModelRenderer(this, 48, 48);
        crown1.addBox(-3.5F, -9.5F, -3.5F, 7, 1, 7);
        crown1.setRotationPoint(0F, 8F, 0F);
        crown1.setTextureSize(256, 128);
        setRotation(crown1, 0F, 0F, 0F);
        crown2 = new ModelRenderer(this, 76, 48);
        crown2.addBox(-3F, -11.2F, -3F, 6, 2, 6);
        crown2.setRotationPoint(0F, 8F, 0F);
        crown2.setTextureSize(256, 128);
        setRotation(crown2, 0F, 0F, 0F);
        crown3 = new ModelRenderer(this, 100, 48);
        crown3.addBox(-2.5F, -13F, -2.5F, 5, 2, 5);
        crown3.setRotationPoint(0F, 8F, 0F);
        crown3.setTextureSize(256, 128);
        setRotation(crown3, 0F, 0F, 0F);
        crown4 = new ModelRenderer(this, 120, 48);
        crown4.addBox(-2F, -14.8F, -2F, 4, 2, 4);
        crown4.setRotationPoint(0F, 8F, 0F);
        crown4.setTextureSize(256, 128);
        setRotation(crown4, 0F, 0F, 0F);
        crown5 = new ModelRenderer(this, 136, 48);
        crown5.addBox(-1.5F, -16.6F, -1.5F, 3, 2, 3);
        crown5.setRotationPoint(0F, 8F, 0F);
        crown5.setTextureSize(256, 128);
        setRotation(crown5, 0F, 0F, 0F);
    }
    
    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        head.render(f5);
        neck.render(f5);
        body.render(f5);
        rightarm.render(f5);
        leftarm.render(f5);
        rightleg.render(f5);
        leftleg.render(f5);
        fronthair1.render(f5);
        fronthair2.render(f5);
        fronthair3.render(f5);
        fronthair4.render(f5);
        rearhair1.render(f5);
        rearhair2.render(f5);
        righthair1.render(f5);
        righthair2.render(f5);
        lefthair1.render(f5);
        lefthair2.render(f5);
        blouse.render(f5);
        rightblouse.render(f5);
        leftblouse.render(f5);
        pants.render(f5);
        rightpants.render(f5);
        leftpants.render(f5);
        rightshoe.render(f5);
        leftshoe.render(f5);
        frontskirt.render(f5);
        rearskirt.render(f5);
        rightskirt.render(f5);
        leftskirt.render(f5);
        frontvest1.render(f5);
        rearvest.render(f5);
        rightvest.render(f5);
        leftvest.render(f5);
        rightshouldervest.render(f5);
        leftshouldervest.render(f5);
        apronribon1.render(f5);
        apronribon2.render(f5);
        apronribon3.render(f5);
        apronribon4.render(f5);
        apronribon5.render(f5);
        apronribon6.render(f5);
        apronribon7.render(f5);
        brim.render(f5);
        crown1.render(f5);
        crown2.render(f5);
        crown3.render(f5);
        crown4.render(f5);
        crown5.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
    
    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
